version: "3.4"

services:
  app:
    image: node:10-alpine
    build:
      context: .
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - WAIT_FOR_POSTGRES
    volumes:
      - .:/app
    depends_on:
      - pg

  pg:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql

  lb:
    image: yvest/lb:1.0
    environment:
      - PROXY_UPSTREAM=app:3000
    ports:
      - 8080:80
